CREATE TABLE bus_stop (
  id SERIAL NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  image_url VARCHAR(128) NOT NULL,
  description TEXT NOT NULL,
  created_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
  updated_at BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)
);

CREATE TRIGGER update_bus_stop_updated_at BEFORE UPDATE ON bus_stop FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
