CREATE TABLE report (
  id SERIAL NOT NULL UNIQUE,
  user_id INTEGER NOT NULL,
  description TEXT NOT NULL,
  location VARCHAR(255) NOT NULL,
  occured_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
  updated_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)
);

CREATE TRIGGER update_report_updated_at BEFORE UPDATE ON report FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
