services:
  backend:
    build:
      context: .
    env_file: .env
    volumes:
      - ./.env:/work/.env:ro
    ports:
      - 5050:5050
    network_mode: "host"
  database:
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  database:
